config/routes.rb
Rails.application.routes.draw do
  resources :task_labels
  resources :labels
  get 'sessions/new'
  resources :users
  root 'tasks#index'
  resources :tasks
  resources :users, only: [:new]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
    
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :fname, presence: true, length: { maximum: 30 }
  validates :lname, presence: true, length: { maximum: 30 }
  validates :password, presence: true, length: { minimum: 6 }
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
  before_validation { email.downcase! }
  has_many :tasks, dependent: :destroy
  has_many :labels, dependent: :destroy

  def self.count_admins
    @users = User.all
    @admins=0
    @users.each do |user|
      if user.user_type == 'admin'
        @admins += 1
      end
    end
    return @admins
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @search = Task.ransack(params[:q])
      if params[:q]
        @tasks = @search.result.page(params[:page])
      elsif params[:sorting_deadline]
        @tasks = Task.all.order('deadline DESC').page(params[:page])
      elsif params[:sorting_priority]
        @tasks = Task.all.order('priority DESC').page(params[:page])
      else
        @tasks = Task.all.order('created_at DESC').page(params[:page])
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id]=@user.id
        format.html { redirect_to admin_users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user.id == current_user.id
      redirect_to admin_users_url, notice: "You are not allowed to delete a signed user"
      @admin = User.count_admins
    elsif @admin == 1
      redirect_to admin_users_url, notice: "At least one admin must remain!"
    else
      @user.destroy
      redirect_to admin_users_url, notice: 'User was successfully destroyed.'
    end
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :user_type, :password, :password_confirmation)
    end

  def admin
    unless current_user.user_type == 'admin'
      redirect_to new_session_path, notice: 'please log in as Admin'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :check_profile]
  before_action :only_see_own_page, only: [:show]
  before_action :admin
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id]=@user.id
        format.html { redirect_to tasks_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :user_type, :password, :password_confirmation)
    end

    def admin
      if logged_in? 
        unless current_user.user_type == 'user'
        redirect_to new_session_path, notice: 'please log in as user'
        end
      end
    end
    def only_see_own_page
      @user = User.find(params[:id])
  
      if current_user != @user
        redirect_to sessions_new_path, notice: "Sorry, but you are only allowed to view your own profile page."
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fname %>
    <%= form.text_field :fname %>
  </div>

  <div class="field">
    <%= form.label :lname %>
    <%= form.text_field :lname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="field">
  <%= form.label :user_type %>
  <%= form.text_field :user_type %>
</div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Email</th>
      <th>User Type</th>
      <th>User Tasks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= user.email %></td>
        <td><%= user.user_type %></td>
        <td><%= link_to 'Show', admin_user_path(user.id) %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

<table class="table table-AZURE">
  <thead>
    <tr>
      <th>Title</th>
      <th>Task</th>
      <th>Status</th>
      <th>Priority</th>
      <th>Deadline</th>
      <th>Created Date</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <% if current_user.id == task.user_id%>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.task_name %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= task.deadline %></td>
        <td><%= task.created_at %></td>
        <td><%= task.user.lname%></td>
        <td><%= link_to 'Show', task, class: 'btn btn-success btn btn-sm' %></td>
        <td><%= link_to 'Edit', edit_task_path(task), class: 'btn btn-primary btn btn-sm' %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn btn-sm' %></td>
      </tr>
      <%end%>
      <% end %>
      </tbody>
      </table>
      
      <%= link_to 'New Task', new_task_path %>
</div>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @user.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @user.lname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>User Type:</strong>
  <%= @user.user_type %>
</p>
<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>